#spring:
#  mail:
#    host: smtp.poczta.onet.pl
#    port: 465
#    username: matix.83@op.pl
#    password: abc123ABC
#    properties:
#      mail.smtp.ssl.enable: true
#      smtp:
#        auth: true
#        starttls:
#          enable: true
#
#logging:
#  level:
#    pl.javastart.zadanie22: DEBUG


